### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by Jamesits**

### CODE REVIEW

**Comment by RalXYZ** [comment]
Thanks a lot! Haven't noticed this because I just wrote this shell script for fun (didn't really take this seriously).  
~The same typo also exists in `README.md`~, so why not fix it by the way, and then I will merge this pr.

**Comment by Jamesits** [comment]
I think I DID fixed the typo in `README.md` :)

**Comment by RalXYZ** [comment]
Oh sorry, then this typo also exists in the shell script, at `moyu.sh:3`

**Comment by Jamesits** [comment]
Updated as requested

**Pull request merged**
